# Generated by Django 4.1.7 on 2023-04-07 14:46

import clients.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='media')),
                ('data_added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='purchaserShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_customer', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=12)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Machakos', 'Machakos'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Busia', 'Busia'), ('Kakamega', 'Kakamega'), ('Nyeri', 'Nyeri'), ('Kampala', 'Kampala'), ('Arusha', 'Arusha'), ('Kigali', 'Kigali'), ('Bujumbura', 'Bujumbura'), ('Pretoria', 'Pretoria'), ('Cape Town', 'Capetown'), ('Johanessburg', 'Johanessburg'), ('Bloemfontein', 'Bloemfontein'), ('Durban', 'Durban'), ('Lagos', 'Lagos'), ('Abuja', 'Abuja')], default='Nairobi', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Tanzania', 'Tanzania'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('South Africa', 'Sa'), ('Nigeria', 'Nigeria')], default='Kenya', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='paymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNo', models.CharField(default=clients.models.increment_invoice_number, max_length=50, unique=True)),
                ('product', models.CharField(blank=True, max_length=20)),
                ('mode', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('Crypto', 'Crypto')], default='Mpesa', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processed', 'Processed'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('payment_made', models.IntegerField(default=0)),
                ('invoiceOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_detail', to='clients.purchaser')),
            ],
        ),
    ]
